### ISSUE TITLE
--predictions vs --raw_predictions

### ISSUE THREAD

**Issue by denik** [jackdoe/turtle#1]
FWIW, it looks like it computes raw predictions (vw -r) rather than predictions (vw -p).

For binary classification, raw prediction is dot product, normal prediction is clipped dot product (+ link function if one is provided).

Compare:

```
$ printf -- '-2 | neg \n 2 | pos \n | pos pos pos pos pos pos pos pos pos pos' | vw --readable_model read.txt --quiet -r /dev/stdout
0
-0.297751
3.034739

$ printf -- '-2 | neg \n 2 | pos \n | pos pos pos pos pos pos pos pos pos pos' | vw --readable_model read.txt --quiet -p /dev/stdout
0
-0.297751
>>> 2 <<<
```

Clipping boundaries are saved in the model:

```
$ head read.txt | grep label
Min label:-2
Max label:2
```

For oaa, regular prediction is class label (calculated as argmax), raw prediction is array of raw scores for each individual model.

**Comment by lucjb** [comment]
Yes. The idea is to add functionality to make it match -p. And one more thing: for --oaa there is also --probabilities which normalises the predictions to sum up to 1 after the link is applied to each class.

**Comment by jackdoe** [comment]
closing as of 73edfc9684030721bf0cb67ff250458eb5665a77
